"""Build data/tracks.csv: hand-picked tracks with audio features.

Source: the Hugging Face dataset maharshipandya/spotify-tracks-dataset (BSD license).
The raw CSV is downloaded to data/raw/ (ignored by git); only the curated
subset is committed.

The dataset's own genre labels are noisy (e.g. Hans Zimmer's "Time" is tagged
"german"), so they are kept as `genre_label` for reference only.
"""

from pathlib import Path

import pandas as pd
from huggingface_hub import hf_hub_download

REPO_ID = "maharshipandya/spotify-tracks-dataset"
PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
OUTPUT_PATH = PROJECT_ROOT / "data" / "tracks.csv"

# (substring of the track name, substring of the artists), grouped by mood so the
# subset covers the whole range: dark to joyful, acoustic to electronic.
CURATED_TRACKS = [
    # Ambient and cinematic
    ("Time", "Hans Zimmer"),
    ("Weightless", "Marconi Union"),
    ("On the Nature of Daylight", "Max Richter"),
    ("An Ending", "Brian Eno"),
    ("Nuvole Bianche", "Einaudi"),
    ("Avril 14th", "Aphex Twin"),
    # Classical and nostalgic
    ("Clair de Lune", "Debussy"),
    ("Gymnopédie No. 1", "Satie"),
    ("Comptine d'un autre été", "Tiersen"),
    ("One Summer Day", "Joe Hisaishi"),
    # Synthwave and electronic
    ("Nightcall", "Kavinsky"),
    ("A Real Hero", "College"),
    ("Blinding Lights", "The Weeknd"),
    ("Midnight City", "M83"),
    ("Little Dark Age", "MGMT"),
    ("Get Lucky", "Daft Punk"),
    ("Firestarter", "The Prodigy"),
    # Trip-hop, dream pop and indie
    ("Teardrop", "Massive Attack"),
    ("Glory Box", "Portishead"),
    ("Playground Love", "Air"),
    ("Space Song", "Beach House"),
    ("Apocalypse", "Cigarettes After Sex"),
    ("Fade Into You", "Mazzy Star"),
    ("Intro", "The xx"),
    ("Nights", "Frank Ocean"),
    # Melancholic singer-songwriters and alternative
    ("Between The Bars", "Elliott Smith"),
    ("Hallelujah", "Jeff Buckley"),
    ("Skinny Love", "Bon Iver"),
    ("Pink Moon", "Nick Drake"),
    ("Karma Police", "Radiohead"),
    # Jazz, soul and retro
    ("Take Five", "Dave Brubeck"),
    ("So What", "Miles Davis"),
    ("Feeling Good", "Nina Simone"),
    ("My Funny Valentine", "Chet Baker"),
    ("Son Of A Preacher Man", "Dusty Springfield"),
    ("Bang Bang", "Nancy Sinatra"),
    # Upbeat and joyful
    ("September", "Earth, Wind"),
    ("Uptown Funk", "Mark Ronson"),
    ("Dancing Queen", "ABBA"),
    ("Don't Stop Me Now", "Queen"),
    ("Here Comes The Sun", "The Beatles"),
    ("Alors on danse", "Stromae"),
    # Rock, metal and hip-hop
    ("Killing In The Name", "Rage Against"),
    ("Smells Like Teen Spirit", "Nirvana"),
    ("Master Of Puppets", "Metallica"),
    ("HUMBLE.", "Kendrick Lamar"),
    ("Beggin'", "Måneskin"),
    ("Comfortably Numb", "Pink Floyd"),
    # French and 80s pop
    ("La vie en rose", "Piaf"),
    ("Sweet Dreams", "Eurythmics"),
    # Songs famously used in a title from data/titles.csv (see data/soundtrack_pairs.csv)
    ("Cornfield Chase", "Hans Zimmer"),
    ("You Never Can Tell", "Chuck Berry"),
    ("Just Like Honey", "Jesus and Mary Chain"),
    ("Baby Blue", "Badfinger"),
    ("Enemy", "Imagine Dragons"),
    ("Tick Of The Clock", "Chromatics"),
    ("Battle Without Honor", "HOTEI"),
    ("Running Up That Hill", "Kate Bush"),
    ("Should I Stay or Should I Go", "The Clash"),
    ("Una Mattina", "Einaudi"),
    ("Fly", "Einaudi"),
    ("Hooked On A Feeling", "Blue Swede"),
    ("Lust For Life", "Iggy Pop"),
    ("Perfect Day", "Lou Reed"),
    ("Where Is My Mind", "Pixies"),
    ("Mrs. Robinson", "Simon & Garfunkel"),
    ("The Sound of Silence", "Simon & Garfunkel"),
    ("Stuck In The Middle With You", "Stealers Wheel"),
    ("Danger Zone", "Kenny Loggins"),
    ("Take My Breath Away", "Berlin"),
    ("Eye of the Tiger", "Survivor"),
    ("Ghostbusters", "Ray Parker"),
    ("Stayin' Alive", "Bee Gees"),
    ("Still Don't Know My Name", "Labrinth"),
    ("Mystery of Love", "Sufjan Stevens"),
    ("Shallow", "Lady Gaga"),
    ("Lose Yourself", "Eminem"),
    ("All The Stars", "Kendrick Lamar"),
    ("Let It Go", "Idina Menzel"),
    ("All Star", "Smash Mouth"),
    ("There Is a Light That Never Goes Out", "The Smiths"),
    ("Don't You (Forget About Me)", "Simple Minds"),
    ("Lux Aeterna", "Clint Mansell"),
    ("Skyfall", "Adele"),
    ("The End", "The Doors"),
    ("Fortunate Son", "Creedence"),
    ("Tiny Dancer", "Elton John"),
    ("Born To Be Wild", "Steppenwolf"),
    ("Circle of Life", "Carmen Twillie"),
    ("Unchained Melody", "Righteous Brothers"),
    ("Oh, Pretty Woman", "Roy Orbison"),
    ("Main Title", "Ramin Djawadi"),
    ("Light of the Seven", "Ramin Djawadi"),
    # Wider catalogue, so more titles have a fitting track
    # Classical
    ("The Four Seasons - Winter", "Vivaldi"),
    ("Moonlight Sonata", "Beethoven"),
    ("Cello Suite No. 1", "Bach"),
    ("Nocturne No. 2", "Chopin"),
    ("Lacrimosa", "Mozart"),
    ("Ride of the Valkyries", "Wagner"),
    ("Swan Lake", "Tchaikovsky"),
    ("Bagatelle No. 25", "Beethoven"),
    # Modern classical
    ("Experience", "Einaudi"),
    ("River Flows In You", "Yiruma"),
    ("Saturn", "Sleeping At Last"),
    ("Says", "Nils Frahm"),
    ("Near Light", "Ólafur Arnalds"),
    # Classic rock
    ("Stairway to Heaven", "Led Zeppelin"),
    ("Immigrant Song", "Led Zeppelin"),
    ("Wish You Were Here", "Pink Floyd"),
    ("Thunderstruck", "AC/DC"),
    ("Highway to Hell", "AC/DC"),
    ("Welcome To The Jungle", "Guns N' Roses"),
    ("Bohemian Rhapsody", "Queen"),
    ("Paint It, Black", "The Rolling Stones"),
    ("Gimme Shelter", "The Rolling Stones"),
    ("Yesterday", "The Beatles"),
    ("Come Together", "The Beatles"),
    ("Riders on the Storm", "The Doors"),
    ("All Along the Watchtower", "Jimi Hendrix"),
    ("Hotel California", "Eagles"),
    ("Sultans Of Swing", "Dire Straits"),
    # Post-punk, new wave and 80s pop
    ("Love Will Tear Us Apart", "Joy Division"),
    ("Just Like Heaven", "The Cure"),
    ("Boys Don't Cry", "The Cure"),
    ("Blue Monday", "New Order"),
    ("Psycho Killer", "Talking Heads"),
    ("Tainted Love", "Soft Cell"),
    ("Everybody Wants To Rule The World", "Tears For Fears"),
    ("Take on Me", "a-ha"),
    ("Africa", "TOTO"),
    ("Don't Stop Believin'", "Journey"),
    ("Every Breath You Take", "The Police"),
    ("Time After Time", "Cyndi Lauper"),
    ("Under Pressure", "Queen"),
    ("Thriller", "Michael Jackson"),
    ("Purple Rain", "Prince"),
    # 90s and 2000s alternative
    ("Creep", "Radiohead"),
    ("Exit Music", "Radiohead"),
    ("No Surprises", "Radiohead"),
    ("Do I Wanna Know?", "Arctic Monkeys"),
    ("Reptilia", "The Strokes"),
    ("Feel Good Inc.", "Gorillaz"),
    ("Clint Eastwood", "Gorillaz"),
    ("In the End", "Linkin Park"),
    ("Chop Suey!", "System Of A Down"),
    ("Du hast", "Rammstein"),
    ("Hurt", "Johnny Cash"),
    ("Seven Nation Army", "The White Stripes"),
    ("Zombie", "The Cranberries"),
    ("Wonderwall", "Oasis"),
    ("Bitter Sweet Symphony", "The Verve"),
    ("Losing My Religion", "R.E.M."),
    ("Black Hole Sun", "Soundgarden"),
    ("Mr. Brightside", "The Killers"),
    # Hip-hop
    ("Still D.R.E.", "Dr. Dre"),
    ("California Love", "2Pac"),
    ("Juicy", "The Notorious B.I.G."),
    ("SICKO MODE", "Travis Scott"),
    ("Gangsta's Paradise", "Coolio"),
    ("C.R.E.A.M.", "Wu-Tang Clan"),
    ("N.Y. State of Mind", "Nas"),
    # Pop
    ("bad guy", "Billie Eilish"),
    ("bury a friend", "Billie Eilish"),
    ("lovely", "Billie Eilish"),
    ("Someone Like You", "Adele"),
    ("Rolling in the Deep", "Adele"),
    ("Starboy", "The Weeknd"),
    ("Take Me To Church", "Hozier"),
    ("Paper Planes", "M.I.A."),
    ("Believer", "Imagine Dragons"),
    # Electronic
    ("Hey Boy Hey Girl", "The Chemical Brothers"),
    ("Roygbiv", "Boards of Canada"),
    ("Archangel", "Burial"),
    ("The Model", "Kraftwerk"),
    ("Angel", "Massive Attack"),
    ("Sandstorm", "Darude"),
    ("Wake Me Up", "Avicii"),
    ("Resonance", "Home"),
    ("Outro", "M83"),
    # Soul, jazz and standards
    ("Ain't No Sunshine", "Bill Withers"),
    ("Dock of the Bay", "Otis Redding"),
    ("Back To Black", "Amy Winehouse"),
    ("At Last", "Etta James"),
    ("What A Wonderful World", "Louis Armstrong"),
    ("Blue in Green", "Miles Davis"),
    ("The Girl From Ipanema", "Stan Getz"),
    ("Imagine", "John Lennon"),
    ("Three Little Birds", "Bob Marley"),
    # Folk, country and indie
    ("Blowin' in the Wind", "Bob Dylan"),
    ("Like a Rolling Stone", "Bob Dylan"),
    ("Hallelujah", "Leonard Cohen"),
    ("Holocene", "Bon Iver"),
    ("Jolene", "Dolly Parton"),
    ("Take Me Home, Country Roads", "John Denver"),
    ("Sweet Home Alabama", "Lynyrd Skynyrd"),
    ("Kids", "MGMT"),
    ("Pumped Up Kicks", "Foster The People"),
    ("Sweater Weather", "The Neighbourhood"),
    ("Riptide", "Vance Joy"),
    ("Ho Hey", "The Lumineers"),
    # Modern pop and indie rock
    ("As It Was", "Harry Styles"),
    ("Watermelon Sugar", "Harry Styles"),
    ("Another Love", "Tom Odell"),
    ("I Wanna Be Yours", "Arctic Monkeys"),
    ("505", "Arctic Monkeys"),
    ("R U Mine?", "Arctic Monkeys"),
    ("Glimpse of Us", "Joji"),
    ("Heat Waves", "Glass Animals"),
    ("Save Your Tears", "The Weeknd"),
    ("The Hills", "The Weeknd"),
    ("Call Out My Name", "The Weeknd"),
    ("Levitating", "Dua Lipa"),
    ("Don't Start Now", "Dua Lipa"),
    ("Titanium", "David Guetta"),
    ("Shape of You", "Ed Sheeran"),
    ("Perfect", "Ed Sheeran"),
    ("Someone You Loved", "Lewis Capaldi"),
    ("drivers license", "Olivia Rodrigo"),
    ("good 4 u", "Olivia Rodrigo"),
    ("Happier Than Ever", "Billie Eilish"),
    ("ocean eyes", "Billie Eilish"),
    ("everything i wanted", "Billie Eilish"),
    ("Blank Space", "Taylor Swift"),
    ("Love Story", "Taylor Swift"),
    ("Hello", "Adele"),
    ("Set Fire to the Rain", "Adele"),
    ("Chandelier", "Sia"),
    ("Counting Stars", "OneRepublic"),
    ("Demons", "Imagine Dragons"),
    ("Stressed Out", "Twenty One Pilots"),
    ("Somebody Told Me", "The Killers"),
    ("When You Were Young", "The Killers"),
    ("Last Nite", "The Strokes"),
    ("Take Me Out", "Franz Ferdinand"),
    ("Song 2", "Blur"),
    ("Fake Plastic Trees", "Radiohead"),
    ("Paranoid Android", "Radiohead"),
    ("Weird Fishes", "Radiohead"),
    ("High and Dry", "Radiohead"),
    # 90s and 2000s rock
    ("Come As You Are", "Nirvana"),
    ("Heart-Shaped Box", "Nirvana"),
    ("The Man Who Sold The World", "Nirvana"),
    ("Where Did You Sleep Last Night", "Nirvana"),
    ("Alive", "Pearl Jam"),
    ("Black", "Pearl Jam"),
    ("Under the Bridge", "Red Hot Chili Peppers"),
    ("Californication", "Red Hot Chili Peppers"),
    ("Scar Tissue", "Red Hot Chili Peppers"),
    ("Can't Stop", "Red Hot Chili Peppers"),
    ("Otherside", "Red Hot Chili Peppers"),
    ("Basket Case", "Green Day"),
    ("Boulevard of Broken Dreams", "Green Day"),
    ("American Idiot", "Green Day"),
    ("Wake Me up When September Ends", "Green Day"),
    ("All The Small Things", "blink-182"),
    ("I Miss You", "blink-182"),
    ("Numb", "Linkin Park"),
    ("Bring Me To Life", "Evanescence"),
    ("Toxicity", "System Of A Down"),
    ("Iris", "The Goo Goo Dolls"),
    ("No Rain", "Blind Melon"),
    ("Tonight, Tonight", "The Smashing Pumpkins"),
    ("Disarm", "The Smashing Pumpkins"),
    ("Bullet With Butterfly Wings", "The Smashing Pumpkins"),
    ("Everlong", "Foo Fighters"),
    ("The Pretender", "Foo Fighters"),
    ("Best of You", "Foo Fighters"),
    ("Welcome to the Black Parade", "My Chemical Romance"),
    ("Teenagers", "My Chemical Romance"),
    ("Sugar, We're Goin Down", "Fall Out Boy"),
    ("Misery Business", "Paramore"),
    ("Decode", "Paramore"),
    ("The Middle", "Jimmy Eat World"),
    ("How to Save a Life", "The Fray"),
    ("Chasing Cars", "Snow Patrol"),
    ("Somewhere Only We Know", "Keane"),
    # Hard rock and metal
    ("Enter Sandman", "Metallica"),
    ("Nothing Else Matters", "Metallica"),
    ("Back In Black", "AC/DC"),
    ("You Shook Me All Night Long", "AC/DC"),
    ("Sweet Child O' Mine", "Guns N' Roses"),
    ("November Rain", "Guns N' Roses"),
    ("Paradise City", "Guns N' Roses"),
    ("Livin' On A Prayer", "Bon Jovi"),
    ("It's My Life", "Bon Jovi"),
    ("Dream On", "Aerosmith"),
    ("I Don't Want to Miss a Thing", "Aerosmith"),
    ("Walk This Way", "Aerosmith"),
    ("Smoke On The Water", "Deep Purple"),
    ("Whole Lotta Love", "Led Zeppelin"),
    ("Kashmir", "Led Zeppelin"),
    ("Another Brick in the Wall, Pt. 2", "Pink Floyd"),
    ("Money", "Pink Floyd"),
    ("Shine On You Crazy Diamond", "Pink Floyd"),
    ("We Will Rock You", "Queen"),
    ("I Want To Break Free", "Queen"),
    ("Duality", "Slipknot"),
    ("Freak On a Leash", "Korn"),
    ("Last Resort", "Papa Roach"),
    ("Break Stuff", "Limp Bizkit"),
    ("Painkiller", "Judas Priest"),
    ("The Trooper", "Iron Maiden"),
    ("Fear of the Dark", "Iron Maiden"),
    ("Crazy Train", "Ozzy Osbourne"),
    ("Holy Diver", "Dio"),
    ("Tom Sawyer", "Rush"),
    ("Carry on Wayward Son", "Kansas"),
    ("Dust in the Wind", "Kansas"),
    ("More Than a Feeling", "Boston"),
    ("La Grange", "ZZ Top"),
    ("Bad To The Bone", "George Thorogood"),
    ("The Beautiful People", "Marilyn Manson"),
    ("Closer", "Nine Inch Nails"),
    ("Down with the Sickness", "Disturbed"),
    # 60s and 70s classics
    ("Let It Be", "The Beatles"),
    ("Hey Jude", "The Beatles"),
    ("Blackbird", "The Beatles"),
    ("Eleanor Rigby", "The Beatles"),
    ("A Day In The Life", "The Beatles"),
    ("While My Guitar Gently Weeps", "The Beatles"),
    ("Sympathy For The Devil", "The Rolling Stones"),
    ("(I Can't Get No) Satisfaction", "The Rolling Stones"),
    ("Angie", "The Rolling Stones"),
    ("Light My Fire", "The Doors"),
    ("People Are Strange", "The Doors"),
    ("Purple Haze", "Jimi Hendrix"),
    ("Little Wing", "Jimi Hendrix"),
    ("Layla", "Derek & The Dominos"),
    ("Tears in Heaven", "Eric Clapton"),
    ("House of the Rising Sun", "The Animals"),
    ("California Dreamin'", "The Mamas & The Papas"),
    ("Rocket Man", "Elton John"),
    ("Your Song", "Elton John"),
    ("I'm Still Standing", "Elton John"),
    ("Piano Man", "Billy Joel"),
    ("Vienna", "Billy Joel"),
    ("Dancing In the Dark", "Bruce Springsteen"),
    ("Born in the U.S.A.", "Bruce Springsteen"),
    ("I'm On Fire", "Bruce Springsteen"),
    ("Heart Of Gold", "Neil Young"),
    ("Harvest Moon", "Neil Young"),
    ("Fast Car", "Tracy Chapman"),
    ("Have You Ever Seen The Rain", "Creedence Clearwater Revival"),
    ("Simple Man", "Lynyrd Skynyrd"),
    ("Free Bird", "Lynyrd Skynyrd"),
    ("The Weight", "The Band"),
    ("For What It's Worth", "Buffalo Springfield"),
    ("Mr. Tambourine Man", "Bob Dylan"),
    ("The Times They Are A-Changin'", "Bob Dylan"),
    ("Knockin' On Heaven's Door", "Bob Dylan"),
    # Punk, post-punk and new wave
    ("London Calling", "The Clash"),
    ("Blitzkrieg Bop", "Ramones"),
    ("I Wanna Be Your Dog", "The Stooges"),
    ("The Passenger", "Iggy Pop"),
    ("Walk On the Wild Side", "Lou Reed"),
    ("Sunday Morning", "The Velvet Underground"),
    ("Heroin", "The Velvet Underground"),
    ("Pale Blue Eyes", "The Velvet Underground"),
    ("Friday I'm In Love", "The Cure"),
    ("Lovesong", "The Cure"),
    ("Pictures Of You", "The Cure"),
    ("This Charming Man", "The Smiths"),
    ("How Soon Is Now?", "The Smiths"),
    ("Disorder", "Joy Division"),
    ("Bizarre Love Triangle", "New Order"),
    ("Age of Consent", "New Order"),
    ("Mad World", "Tears For Fears"),
    ("Shout", "Tears For Fears"),
    ("Head Over Heels", "Tears For Fears"),
    ("Heart Of Glass", "Blondie"),
    ("Call Me", "Blondie"),
    ("Girls Just Want to Have Fun", "Cyndi Lauper"),
    ("Wake Me Up Before You Go-Go", "Wham!"),
    ("Wuthering Heights", "Kate Bush"),
    ("Cloudbusting", "Kate Bush"),
    # More electronic
    ("Children", "Robert Miles"),
    ("Insomnia", "Faithless"),
    ("Smack My Bitch Up", "The Prodigy"),
    ("Breathe", "The Prodigy"),
    ("Block Rockin' Beats", "The Chemical Brothers"),
    ("Galvanize", "The Chemical Brothers"),
    ("Windowlicker", "Aphex Twin"),
    ("Xtal", "Aphex Twin"),
    ("Strobe", "deadmau5"),
    ("Animals", "Martin Garrix"),
    ("Lean On", "Major Lazer"),
    ("Faded", "Alan Walker"),
    ("Wait", "M83"),
    ("A Moment Apart", "ODESZA"),
    ("Kiara", "Bonobo"),
    ("Kong", "Bonobo"),
    ("Cirrus", "Bonobo"),
    ("Dayvan Cowboy", "Boards of Canada"),
    ("Music Is Math", "Boards of Canada"),
    ("Immunity", "Jon Hopkins"),
    ("Tubular Bells", "Mike Oldfield"),
    ("Moonlight Shadow", "Mike Oldfield"),
    ("Kernkraft 400", "Zombie Nation"),
    ("Call on Me", "Eric Prydz"),
    ("Instant Crush", "Daft Punk"),
    ("Sexy Boy", "Air"),
    ("La femme d'argent", "Air"),
    ("All I Need", "Air"),
    ("Cherry Blossom Girl", "Air"),
    ("Kelly Watch the Stars", "Air"),
    ("Heartbeats", "The Knife"),
    ("Heartbeats", "José González"),
    ("Bloodstream", "Stateless"),
    # More hip-hop and R&B
    ("goosebumps", "Travis Scott"),
    ("God's Plan", "Drake"),
    ("One Dance", "Drake"),
    ("Without Me", "Eminem"),
    ("The Real Slim Shady", "Eminem"),
    ("Stan", "Eminem"),
    ("Till I Collapse", "Eminem"),
    ("In Da Club", "50 Cent"),
    ("Hypnotize", "The Notorious B.I.G."),
    ("Big Poppa", "The Notorious B.I.G."),
    ("Changes", "2Pac"),
    ("Dear Mama", "2Pac"),
    ("Forgot About Dre", "Dr. Dre"),
    ("Drop It Like It's Hot", "Snoop Dogg"),
    ("Shook Ones, Pt. II", "Mobb Deep"),
    ("Old Town Road", "Lil Nas X"),
    ("Pink + White", "Frank Ocean"),
    ("Thinkin Bout You", "Frank Ocean"),
    ("Ivy", "Frank Ocean"),
    ("Self Control", "Frank Ocean"),
    # More indie
    ("Electric Feel", "MGMT"),
    ("Time to Pretend", "MGMT"),
    ("Somebody Else", "The 1975"),
    ("Robbers", "The 1975"),
    ("Young Folks", "Peter Bjorn and John"),
    ("Home", "Edward Sharpe"),
    ("The Night We Met", "Lord Huron"),
    ("Ophelia", "The Lumineers"),
    ("I Will Wait", "Mumford & Sons"),
    ("Little Talks", "Of Monsters and Men"),
    ("Budapest", "George Ezra"),
    ("Let Her Go", "Passenger"),
    ("Work Song", "Hozier"),
    ("Motion Sickness", "Phoebe Bridgers"),
    ("Moon Song", "Phoebe Bridgers"),
    ("Sunsetz", "Cigarettes After Sex"),
    ("K.", "Cigarettes After Sex"),
    ("Nothing's Gonna Hurt You Baby", "Cigarettes After Sex"),
    # Oldies, soul and disco
    ("Blue Velvet", "Bobby Vinton"),
    ("In Dreams", "Roy Orbison"),
    ("Crying", "Roy Orbison"),
    ("Only You", "The Platters"),
    ("Johnny B. Goode", "Chuck Berry"),
    ("Jailhouse Rock", "Elvis Presley"),
    ("Can't Help Falling in Love", "Elvis Presley"),
    ("Suspicious Minds", "Elvis Presley"),
    ("Stand by Me", "Ben E. King"),
    ("My Girl", "The Temptations"),
    ("Ain't No Mountain High Enough", "Marvin Gaye"),
    ("I Want You Back", "The Jackson 5"),
    ("Man in the Mirror", "Michael Jackson"),
    ("Rock with You", "Michael Jackson"),
    ("Lovely Day", "Bill Withers"),
    ("Lean on Me", "Bill Withers"),
    ("Just the Two of Us", "Grover Washington"),
    ("I Say a Little Prayer", "Aretha Franklin"),
    ("A Natural Woman", "Aretha Franklin"),
    ("Valerie", "Amy Winehouse"),
    ("Rehab", "Amy Winehouse"),
    ("You Know I'm No Good", "Amy Winehouse"),
    ("Love Is A Losing Game", "Amy Winehouse"),
    ("I Will Survive", "Gloria Gaynor"),
    ("Le Freak", "CHIC"),
    ("Good Times", "CHIC"),
    ("Boogie Wonderland", "Earth, Wind & Fire"),
    ("Let's Groove", "Earth, Wind & Fire"),
    ("More Than A Woman", "Bee Gees"),
    ("How Deep Is Your Love", "Bee Gees"),
    ("Disco Inferno", "The Trammps"),
    ("Hot Stuff", "Donna Summer"),
    ("I Feel Love", "Donna Summer"),
    ("Gimme! Gimme! Gimme!", "ABBA"),
    ("Mamma Mia", "ABBA"),
    ("The Winner Takes It All", "ABBA"),
    ("Waterloo", "ABBA"),
    # Latin and reggae
    ("Despacito", "Luis Fonsi"),
    ("Hips Don't Lie", "Shakira"),
    ("Whenever, Wherever", "Shakira"),
    ("Danza Kuduro", "Don Omar"),
    ("Gasolina", "Daddy Yankee"),
    ("Livin' la Vida Loca", "Ricky Martin"),
    ("La Bamba", "Ritchie Valens"),
    ("Oye Como Va", "Santana"),
    ("Smooth", "Santana"),
    ("Black Magic Woman", "Santana"),
    ("Is This Love", "Bob Marley"),
    ("Could You Be Loved", "Bob Marley"),
    ("Redemption Song", "Bob Marley"),
    ("One Love", "Bob Marley"),
    ("Jamming", "Bob Marley"),
    ("Bad Boys", "Inner Circle"),
    ("Red Red Wine", "UB40"),
    # More jazz and standards
    ("Summertime", "Louis Armstrong"),
    ("Dream A Little Dream Of Me", "Ella Fitzgerald"),
    ("Cheek To Cheek", "Ella Fitzgerald"),
    ("L-O-V-E", "Nat King Cole"),
    ("Unforgettable", "Nat King Cole"),
    ("Beyond the Sea", "Bobby Darin"),
    ("Mack the Knife", "Bobby Darin"),
    ("Sway", "Dean Martin"),
    ("That's Amore", "Dean Martin"),
    ("I Put A Spell On You", "Nina Simone"),
    ("Sinnerman", "Nina Simone"),
    ("Don't Let Me Be Misunderstood", "Nina Simone"),
    ("In A Sentimental Mood", "Duke Ellington"),
    ("'Round Midnight", "Thelonious Monk"),
    ("Cantaloupe Island", "Herbie Hancock"),
    # More classical and modern classical
    ("Gnossienne No. 1", "Erik Satie"),
    ("Deux Arabesques", "Claude Debussy"),
    ("Fantaisie-Impromptu", "Chopin"),
    ("Piano Concerto No. 21", "Mozart"),
    ("Goldberg Variations", "Bach"),
    ("The Well-Tempered Clavier", "Bach"),
    ("Habanera", "Bizet"),
    ("Nessun", "Puccini"),
    ("Gianni Schicchi", "Puccini"),
    ("La donna è mobile", "Verdi"),
    ("Méditation from Thaïs", "Massenet"),
    ("The Hours", "Philip Glass"),
    ("Truman Sleeps", "Philip Glass"),
    ("La Valse d'Amélie", "Yann Tiersen"),
    ("Divenire", "Ludovico Einaudi"),
    ("Primavera", "Ludovico Einaudi"),
    ("I Giorni", "Ludovico Einaudi"),
    ("Le Onde", "Ludovico Einaudi"),
    ("Elegy For The Arctic", "Ludovico Einaudi"),
    ("The Departure", "Max Richter"),
    ("Vladimir's Blues", "Max Richter"),
    ("Spring 1", "Max Richter"),
    ("November", "Max Richter"),
    ("Written on the Sky", "Max Richter"),
    ("Flight from the City", "Jóhann Jóhannsson"),
    ("A Model of the Universe", "Jóhann Jóhannsson"),
    ("saman", "Ólafur Arnalds"),
    ("Only The Winds", "Ólafur Arnalds"),
    ("Ambre", "Nils Frahm"),
    # Country
    ("9 to 5", "Dolly Parton"),
    ("Tennessee Whiskey", "Chris Stapleton"),
    ("The Gambler", "Kenny Rogers"),
    ("Wagon Wheel", "Darius Rucker"),
]

COLUMNS = {
    "track_id": "track_id",
    "track_name": "title",
    "artists": "artist",
    "album_name": "album",
    "track_genre": "genre_label",
    "popularity": "popularity",
    "danceability": "danceability",
    "energy": "energy",
    "valence": "valence",
    "acousticness": "acousticness",
    "instrumentalness": "instrumentalness",
    "tempo": "tempo",
}


def load_raw_dataset() -> pd.DataFrame:
    """Download the raw CSV once, then read it (the first column is just a row index)."""
    path = hf_hub_download(REPO_ID, "dataset.csv", repo_type="dataset", local_dir=RAW_DIR)
    return pd.read_csv(path, index_col=0)


def find_track(dataset: pd.DataFrame, name: str, artist: str) -> pd.Series:
    """Return the most popular row whose title and artists contain the given substrings."""
    matches = dataset[
        dataset["track_name"].str.contains(name, case=False, regex=False, na=False)
        & dataset["artists"].str.contains(artist, case=False, regex=False, na=False)
    ]
    if matches.empty:
        raise SystemExit(f"Track not found in the dataset: {name!r} by {artist!r}")
    return matches.sort_values("popularity", ascending=False).iloc[0]


def main() -> None:
    dataset = load_raw_dataset()
    rows = [find_track(dataset, name, artist) for name, artist in CURATED_TRACKS]

    tracks = pd.DataFrame(rows)[list(COLUMNS)].rename(columns=COLUMNS)
    tracks["artist"] = tracks["artist"].str.replace(";", ", ", regex=False)

    duplicated = tracks["track_id"].duplicated()
    if duplicated.any():
        raise SystemExit(f"Duplicate tracks picked: {tracks.loc[duplicated, 'title'].tolist()}")

    OUTPUT_PATH.parent.mkdir(exist_ok=True)
    tracks.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved {len(tracks)} tracks to {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
